package waterflow.domain.exceptions;

public enum ExceptionCodes {
    NEGATIVE_VOLUME,
    WATER_OVERFLOW,
    SAFETY_THRESHOLD,
    CONTAINER_ALREADY_FULL,
    WATER_FLOW_SESSION,
    INVALID_VOLUME_TYPE,
    INVALID_TIME_MEASUREMENT_UNIT,
    WATER_PUMP_IN_USE
}
